FROM node:alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./

RUN npm install
COPY --chown=node:node . /app 
# RUN npm config set unsafe-perm true
# RUN chown -R node:node . 
CMD ["npm","start"]